field: e567b6ab-3855-452b-a337-4c119dac4d62 # Body Content
fieldLayouts:
  59ffc94b-a1a3-4ecb-98e4-67dbd4317f23:
    tabs:
      -
        elements:
          -
            fieldUid: df3a27ff-e318-422f-8ff5-d626eda8ce54 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  df3a27ff-e318-422f-8ff5-d626eda8ce54: # Rich Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: ''
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
