color: null
fieldLayouts:
  d0baa120-b528-4317-a11e-0a36f80501c3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b203fd7-eca1-4313-8795-efbb5f6a8e63 # Body Content - Image - Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1ad0bac-ef1a-475f-96dc-2ae14f2766f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d2372e2-c220-4af4-80c9-49bb8c85a92e # Body Content - Image - Position
            handle: null
            includeInCards: true
            instructions: null
            label: Position
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 530b405b-3e1e-4c46-a0c2-e6f0348272d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 249743ae-e9a8-41ce-b286-4782bff3be44
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
