columnSuffix: null
contentColumnType: string
fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb # Common
handle: bodyContent
instructions: ''
name: 'Body Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_bodycontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
