contentColumnType: text
fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb # Common
handle: summary
instructions: 'Summary for the blog index'
name: Summary
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
