enableVersioning: true
handle: about
name: About
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  f3400d6f-0f33-4cef-9521-f8f6620399ec: # Craft Blog
    enabledByDefault: true
    hasUrls: true
    template: _private/about
    uriFormat: about
type: single
