defaultPlacement: end
enableVersioning: true
entryTypes:
  - bb6d289b-c3cf-4a8d-9324-b98cbd32753b # Post
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Gatsby entry page'
      -
        - urlFormat
        - '@gatsby/{uri}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  f3400d6f-0f33-4cef-9521-f8f6620399ec: # Craft Blog
    enabledByDefault: true
    hasUrls: true
    template: _private/blog-entry
    uriFormat: 'blog/{slug}'
type: channel
